version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: ./dockerfiles/production/Dockerfile
    container_name: recipe_frontend
    restart: always
    ports:
      - 80:4200
