version: '3.6'

services:
  frontend:
    container_name: mspr-recipe-frontend
    build:
      context: .
      dockerfile: ./dockerfiles/production/Dockerfile
    restart: always
    ports:
    - 80:80
